version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      SPRING_PROFILES_ACTIVE: prod

      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/musicdb
      SPRING_DATASOURCE_USERNAME: seplag
      SPRING_DATASOURCE_PASSWORD: seplag123

      MINIO_INTERNAL_URL: http://minio:9000
      MINIO_PUBLIC_URL: http://localhost:9000
      MINIO_ACCESS_KEY: seplag
      MINIO_SECRET_KEY: seplag123
      MINIO_BUCKET_NAME: albums

      JWT_SECRET: c2VwbGFnLXN1cGVyLXNlY3JldC1rZXktZm9yLWp3dC1zaWduaW5nLTI1Ni1iaXRzLW1pbmltdW0=
      TZ: America/Cuiaba
    depends_on:
      - database
      - minio
      - minio-init
    networks:
      - seplag-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - seplag-network

  database:
    image: postgres:16
    container_name: database
    environment:
      POSTGRES_USER: seplag
      POSTGRES_PASSWORD: seplag123
      POSTGRES_DB: musicdb
    ports:
      - "5432:5432"
    networks:
      - seplag-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: seplag
      MINIO_ROOT_PASSWORD: seplag123
    command: server /data --console-address ":9001"
    networks:
      - seplag-network
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc
    container_name: minio-init
    depends_on:
      - minio
    networks:
      - seplag-network
    entrypoint: >
      /bin/sh -c "
      until (mc alias set local http://minio:9000 seplag seplag123) do
        echo 'Aguardando MinIO...';
        sleep 2;
      done;

      mc mb -p local/albums || true;
      mc anonymous set download local/albums || true;

      echo '✅ Bucket albums pronto e público (download)';
      "

networks:
  seplag-network:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
