version: '3.8'

services:
  backend:
    image: fogeid/seplag-api
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      # Spring Profile
      SPRING_PROFILES_ACTIVE: prod
      
      # Database
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/musicdb
      SPRING_DATASOURCE_USERNAME: seplag
      SPRING_DATASOURCE_PASSWORD: seplag123
      
      # MinIO
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: seplag
      MINIO_SECRET_KEY: seplag123
      MINIO_BUCKET_NAME: albums
      
      # JWT
      JWT_SECRET: c2VwbGFnLXN1cGVyLXNlY3JldC1rZXktZm9yLWp3dC1zaWduaW5nLTI1Ni1iaXRzLW1pbmltdW0=
      
      # Timezone
      TZ: America/Cuiaba
    networks:
      - seplag-network
    depends_on:
      - database
      - minio

  database:
    image: postgres:16
    container_name: database
    environment:
      POSTGRES_USER: seplag
      POSTGRES_PASSWORD: seplag123
      POSTGRES_DB: musicdb
    ports:
      - "5432:5432"
    networks:
      - seplag-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: seplag
      MINIO_ROOT_PASSWORD: seplag123
    command: server /data --console-address ":9001"
    networks:
      - seplag-network
    volumes:
      - minio_data:/data

networks:
  seplag-network:
    driver: bridge

volumes:
  postgres_data:
  minio_data: